package com.flowerconnect.catalog.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * Request body for category create and update (plan task 3.1).
 *
 * <p>The slug is <em>not</em> accepted from the client: it is generated by
 * the service from {@code name} with a collision-safe suffix, so two
 * categories cannot share a slug and the admin never has to type one. The
 * field is therefore absent from this DTO rather than optional-with-a-null
 * sentinel, which would let a client send an arbitrary slug.
 *
 * <p>{@code parentId} is nullable: a null value means "top-level category".
 * {@code displayOrder} defaults to 0; rows sort by (parent_id,
 * display_order, id) so ties are stable.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CategoryRequest {

    @NotBlank(message = "Category name is required")
    @Size(max = 128, message = "Category name must be at most 128 characters")
    private String name;

    private Long parentId;

    private Integer displayOrder;

    private Boolean active;
}