package com.flowerconnect.catalog.dto;

import com.flowerconnect.catalog.domain.Product.ProductStatus;
import jakarta.validation.constraints.*;
import lombok.*;

import java.math.BigDecimal;

/**
 * Request body for product create and update (plan task 3.2).
 *
 * <p>The slug is <em>not</em> accepted from the client: it is
 * generated by the service from {@code name} with a
 * collision-safe suffix, so two products cannot share a slug and
 * the vendor never has to type one. The field is absent from this
 * DTO rather than optional-with-a-null sentinel, which would let a
 * client send an arbitrary slug.
 *
 * <p>{@code status} is optional on create and defaults to
 * {@code DRAFT}: a product is invisible until the vendor
 * explicitly activates it.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProductRequest {

    @NotBlank(message = "Product name is required")
    @Size(max = 160, message = "Product name must be at most 160 characters")
    private String name;

    @NotNull(message = "Category is required")
    private Long categoryId;

    @Size(max = 2000, message = "Description must be at most 2000 characters")
    private String description;

    @NotNull(message = "Base price is required")
    @DecimalMin(value = "0.00", message = "Base price must not be negative")
    @Digits(integer = 8, fraction = 2, message = "Base price must have at most 8 integer and 2 fraction digits")
    private BigDecimal basePrice;

    private ProductStatus status;
}
