package com.flowerconnect.catalog.domain;

import com.flowerconnect.domain.VendorProfile;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * A vendor-managed catalog entry (plan task 3.2).
 *
 * <p>A product belongs to exactly one vendor (the owner) and one
 * admin-managed {@link Category}. Images live in
 * {@code ProductImage}, never in a JSON column on this table, and
 * the stock level lives in the {@code inventory} table — one row
 * per product, created in the same transaction as the product.
 *
 * <p>{@code slug} is the canonical client-facing identifier. It is
 * generated by {@code ProductService} from {@code name} with a
 * collision-safe numeric suffix; the unique constraint is the
 * authority and the service retries on violation, so two products
 * can never share a slug even under a concurrent create.
 *
 * <p>{@code status} controls storefront visibility:
 * <ul>
 *   <li>{@code DRAFT} — the vendor is still editing it; not visible</li>
 *   <li>{@code ACTIVE} — visible in the storefront</li>
 *   <li>{@code INACTIVE} — hidden but not deleted</li>
 *   <li>{@code ARCHIVED} — end of life; not visible</li>
 * </ul>
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Builder
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vendor_id", nullable = false)
    private VendorProfile vendor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    @Column(name = "name", length = 160, nullable = false)
    private String name;

    @Column(name = "slug", length = 160, nullable = false)
    private String slug;

    @Column(name = "description", length = 2000)
    private String description;

    @Column(name = "base_price", precision = 10, scale = 2, nullable = false)
    private BigDecimal basePrice;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private ProductStatus status;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Lifecycle state of a product. Only {@code ACTIVE} is storefront-visible. */
    public enum ProductStatus {
        DRAFT, ACTIVE, INACTIVE, ARCHIVED
    }
}
