-- FlowerConnect V7__categories.sql
-- Phase 3a (plan v2.2 task 3.1): the catalog category hierarchy.
--
-- `categories` is a small, admin-managed lookup that vendors read and assign
-- products to. It is hierarchical so a product can live under a leaf
-- (e.g. "Roses > Hybrid Tea") while the top level is what category chips show.
--
-- Design notes:
--   * `parent_id` is nullable: NULL marks a top-level category, and the FK
--     references the same table so the depth is unbounded. Cycle prevention
--     (a category may not become its own ancestor) is enforced in
--     `CategoryService`, not by the database, because a CHECK constraint
--     cannot walk a chain.
--   * `slug` is unique and is the canonical client-facing identifier. It is
--     generated by the service from `name` with a collision-safe suffix, so
--     two categories cannot share a slug and the admin does not have to type
--     one. The seed rows carry slugs explicitly for the same reason V4 seeds
--     pincodes explicitly: deterministic, reviewable, and idempotent.
--   * `display_order` lets an admin reorder the top-level chips without
--     touching the database by hand; rows sort by (parent_id, display_order,
--     id) so ties are stable.
--   * `active` is a soft flag. Inactive categories are hidden from the
--     public read endpoint and from product assignment but their rows are
--     kept, so reactivating is a column update rather than a re-insert.
--
-- This migration is additive: no existing table, column, constraint or index
-- is altered or dropped, and no existing row is touched.

CREATE TABLE categories (
    id            BIGINT         NOT NULL AUTO_INCREMENT,
    parent_id     BIGINT         NULL,
    name          VARCHAR(128)   NOT NULL,
    slug          VARCHAR(128)   NOT NULL,
    display_order INT            NOT NULL DEFAULT 0,
    active        BIT(1)         NOT NULL DEFAULT b'1',
    created_at    DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at    DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_slug UNIQUE (slug),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_categories_parent ON categories (parent_id);
CREATE INDEX idx_categories_display_order ON categories (parent_id, display_order, id);

-- Seed data: the four top-level categories the plan names (Roses, Bouquets,
-- Arrangements, Occasions). parent_id is NULL because they are the roots.
-- Slugs are the kebab-case form of the name; display_order defines the
-- default chip order on the customer home page.
INSERT INTO categories (name, slug, display_order) VALUES
    ('Roses',       'roses',       1),
    ('Bouquets',    'bouquets',    2),
    ('Arrangements','arrangements',3),
    ('Occasions',   'occasions',   4);