-- FlowerConnect V8__products.sql
-- Phase 3b (plan v2.2 task 3.2): product catalog.
--
-- `products` is the vendor-managed catalog entry. Vendors create, update and
-- delete their own products; admins can see all. Products are assigned to a
-- single admin-managed category and carry a slug that is generated by the
-- service (collision-safe suffix) so vendors never have to type one.
--
-- Design notes:
--   * `vendor_id` is the authoritative owner. A product is never unowned.
--   * `category_id` references the admin-managed `categories` table. The FK
--     is mandatory so every product belongs to a category; if a category is
--     deactivated, existing products stay assigned but are hidden from the
--     public read endpoint.
--   * `slug` is unique and is the canonical client-facing identifier. It is
--     generated by `ProductService` from `name` with a collision-safe suffix.
--   * `status` controls visibility: `DRAFT` (vendor editing, not visible),
--     `ACTIVE` (visible in storefront), `INACTIVE` (hidden, not deleted),
--     `ARCHIVED` (end-of-life, not visible). Admin can override; vendor can
--     only move between `DRAFT`, `ACTIVE`, `INACTIVE`.
--   * `base_price` uses DECIMAL(10,2) for INR with two decimal places.
--   * Images are NOT stored on this table — they live in `product_images`.
--
-- This migration is additive: no existing table, column, constraint or index
-- is altered or dropped, and no existing row is touched.

CREATE TABLE products (
    id            BIGINT         NOT NULL AUTO_INCREMENT,
    vendor_id     BIGINT         NOT NULL,
    category_id   BIGINT         NOT NULL,
    name          VARCHAR(160)   NOT NULL,
    slug          VARCHAR(160)   NOT NULL,
    description   VARCHAR(2000)  NULL,
    base_price    DECIMAL(10,2)  NOT NULL,
    status        ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    created_at    DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at    DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_slug UNIQUE (slug),
    CONSTRAINT fk_products_vendor FOREIGN KEY (vendor_id) REFERENCES vendor_profiles (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_products_vendor ON products (vendor_id);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_status ON products (status);
CREATE INDEX idx_products_vendor_status ON products (vendor_id, status);