package com.flowerconnect.storage;

/**
 * Byte storage for uploaded assets (plan task 3.8: "Local disk (dev) / S3 (prod)
 * behind {@code StorageService} — pluggable by profile").
 *
 * <p>The interface deliberately knows nothing about images. It is a flat
 * key/value store, so the same abstraction can hold product images today and
 * any other binary asset later, and so swapping the backend cannot change a
 * single call site in the domain layer.
 *
 * <h2>Key contract</h2>
 * <ul>
 *   <li>A key is <b>always generated by the server</b>. No client-supplied
 *       value ever becomes a key. The vendor's filename is kept in
 *       {@code product_images.original_filename} for display and is never
 *       used as a path.</li>
 *   <li>A key is {@code /}-separated, relative, and must stay inside the
 *       backend's root. Implementations reject absolute keys, keys containing a
 *       backslash, and any key that resolves outside the root, so path
 *       traversal is refused at the boundary rather than normalised away.</li>
 * </ul>
 *
 * <h2>Failure contract</h2>
 * Storage failures are infrastructure failures and surface as
 * {@link StorageException} (HTTP 500). They are never converted into a client
 * error: telling a caller "storage failed" invites a retry that is exactly
 * what a backend outage makes worse. The caller's own validation (size, type,
 * count, ownership) happens before a single byte is written, so a
 * {@link StorageException} from {@link #store} means the write itself failed
 * and no row should be kept.
 */
public interface StorageService {

    /**
     * Writes {@code content} at {@code key}, replacing any object already
     * stored there.
     *
     * @throws StorageException         if the object cannot be written
     * @throws IllegalArgumentException if the key is blank, absolute, contains a
     *                                  backslash, or resolves outside the root
     */
    void store(String key, byte[] content);

    /**
     * Removes the object at {@code key}. Deleting a key that does not exist is a
     * no-op, so a compensating delete after a rolled-back transaction is safe to
     * call unconditionally.
     */
    void delete(String key);

    /** Whether an object exists at {@code key}. */
    boolean exists(String key);

    /**
     * Human-readable description of where this backend writes (directory or
     * bucket), used in log lines. Never includes credentials.
     */
    String describe();
}